config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :locations
  resource :registration
  resource :session
  resource :password_reset
  resources :password


  resources :todos, only: [:index, :create]
  get '/todos', to: 'todos#task'


  get "up" => "rails/health#show", as: :rails_health_check


  get "sign_up", to: "registrations#new"
  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :location
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, uniqueness: true
    normalizes :email, with: ->(email) {email.strip.downcase}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private 

    def authenticate_user!
        redirect_to root_path, alert: "You mush be logged in to do that" unless user_signed_in?
    end
    def current_user
        Current.user ||= authenticate_user_from_session
    end
    helper_method :current_user

    def authenticate_user_from_session
        User.find_by(id: session[:user_id])
    end

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?	

    def login(user)
        Current.user = user
        reset_session
        session[:user_id] = user.id
    end

    def logout(user)
        Current.user = nil
        reset_session
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy ]

  # GET /locations or /locations.json
  def index
    @locations = Location.all
    if params[:place].present?
      @locations = Location.near(params[:place], params[:distance] || 10, order: :distance)
    else
      @locations = Location.all
    end
  end

  # GET /locations/1 or /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to location_url(@location), notice: "Location was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to location_url(@location), notice: "Location was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy!

    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:name, :address, :latitude, :longitude)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :authenticate_user!

    def edit
    end

    def update
        if current_user.update(password_params)
            redirect_to edit_password_path, notice: "Password updated."
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private 

    def password_params
        params.require(:user).permit(:password, :password_confirmation, :password_challenge).with_defaults(password_challenge: "")
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(registration_params)

    if @user.save
      login @user
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def registration_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        if user = User.authenticate_by(email: params[:email], password: params[:password])
            login user
            redirect_to root_path, notice: "You have been logged in."
        else
            flash.now[:alert] = "Invalid email or password."
            render :new, status: :unprocessable_entity
        end
    end

    
    def destroy
        logout current_user
        redirect_to root_path, notice: "You have been logged out."
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy!

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:description, :location_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Tmap</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
   <%= javascript_include_tag 'current_location' %> 
   
  <style>
    .navbar {
      background-color: #007bff !important;
      border: none !important;
    }
    .navbar-brand {
      color: #fff;
    }
    .navbar-nav .nav-link {
      color: #fff;
    }
    .nav-item {
      margin-left: 10px;
    }
    
  </style>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container">
    <%= link_to "Tmap", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item" style='background-collor:#007bff'>
            <%= link_to "Log out", session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log in", new_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container mt-4">
  <!-- Flash Messages -->
  <div><%= notice %></div>
  <div><%= alert %></div>

  <!-- Main Content -->
  <%= yield %>
</div>

<!-- Bootstrap JS (optional) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/locations/_location.html.erb
<div id="<%= dom_id location %>">
  <p>
    <strong>Name:</strong>
    <%= location.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= location.address %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= location.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= location.longitude %>
  </p>

</div>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Show this location", @location %> |
  <%= link_to "Back to locations", locations_path %>
</div>

app/views/locations/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Locations</title>
  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <style>
    /* Custom Styles */
    body {
      background-color: #f8f9fa;
    }
  </style>
</head>
<body>
  <div class="container">
    <% if notice.present? %>
      <p class="alert alert-success mt-3"><%= notice %></p>
    <% end %>

    <h1 class="mt-4">Locations</h1>

    <%= form_with url: locations_path, method: :get, class: "mt-3 mb-3" do |form| %>
      <div class="input-group">
        <%= form.text_field :place, value: params[:place], class: "form-control" %>
        <div class="input-group-append">
          <%= form.submit "Search", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  
  
    <div id="locations" class="mt-4">
      <% @locations.each do |location| %>
        <%= render location %>
        <p>
          <%= link_to "Show this location", location, class: "btn btn-secondary" %>
        </p>
      <% end %>
    </div>

    <%= link_to "New Location", new_location_path, class: "btn btn-success mt-4" %>
  </div>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/locations/new.html.erb
<head>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<h1>New location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Back to locations", locations_path %>
</div>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

app/views/locations/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Location Details</title>
  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <div class="container">
    <div class="alert alert-success mt-3" role="alert">
      <%= notice %>
    </div>

    <%= render @location %>

    <div class="mt-3">
      <%= link_to "Edit this location", edit_location_path(@location), class: "btn btn-primary mr-2" %>
      <%= link_to "Back to locations", locations_path, class: "btn btn-secondary mr-2" %>
      <%= button_to "Destroy this location", @location, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </div>
  </div>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/main/index.html.erb
<h1>Homepage</h1>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.select :location_id, Location.all.collect { |l| [l.name, l.id] }, { include_blank: "Select a location" } %>

  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>" class="card todo-item">
  <div class="card-body">
    <h5 class="card-title"style="color:#007bff">Task Description</h5>
    <p class="card-text"><strong>Description:</strong> <%= todo.description %></p>
    <h5 class="card-title" style="color:#007bff">Location</h5>
    <p class="card-text"><strong>Location:</strong> <%= todo.location.name %></p>
  </div>
</div>

app/views/todos/edit.html.erb
<div class="container">
  <h1 class="mt-5 mb-4">Editing Todo</h1>

  <%= render "form", todo: @todo %>

  <div class="mt-4">
    <%= link_to "Show this todo", @todo, class: "btn btn-primary mr-2" %> |
    <%= link_to "Back to todos", todos_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/todos/index.html.erb
<!DOCTYPE html>

<html>
  <head>
    <script>
      
      function initMap() {
        const map = new google.maps.Map(document.getElementById("map"), {
          center: { lat: 46.362274, lng: 15.110658 },
          zoom: 9,
          mapTypeControl: false,
        });

        <% @todos.each do |todo| %>
          // Create a marker for each todo
          const marker_<%= todo.id %> = new google.maps.Marker({
            position: { lat: <%= todo.location.latitude %>, lng: <%= todo.location.longitude %> },
            map: map,
            description: '<%= todo.description %>' // optional: display description on marker
            


          });

          marker_<%= todo.id %>.addListener("click", () => {
            const infowindow = new google.maps.InfoWindow({
              content: `<h3>${marker_<%= todo.id %>.description}</h3>
              <a href="/todos/<%= todo.id %>" data-method="delete" data-confirm="Are you sure?" data-turbo-frame="_top">Poglej</a>`
            });
            infowindow.open(map, marker_<%= todo.id %>);
          });
          

        <% end %>
      }
      showCurrentLocation(Map);
      window.initMap = initMap;
    </script>
    <style>
      
      #map {
        height: 500px;
      }

      
      html,
      body {
        height: 100%;
        margin: 0;
        padding: 0;
      }

      #description {
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
      }

      #infowindow-content .title {
        font-weight: bold;
      }

      #infowindow-content {
        display: none;
      }

      #map #infowindow-content {
        display: inline;
      }

      .pac-card {
        background-color: #fff;
        border: 0;
        border-radius: 2px;
        box-shadow: 0 1px 4px -1px rgba(0, 0, 0, 0.3);
        margin: 10px;
        padding: 0 0.5em;
        font: 400 18px Roboto, Arial, sans-serif;
        overflow: hidden;
        font-family: Roboto;
        padding: 0;
      }

      #pac-container {
        padding-bottom: 12px;
        margin-right: 12px;
      }

      .pac-controls {
        display: inline-block;
        padding: 5px 11px;
      }

      .pac-controls label {
        font-family: Roboto;
        font-size: 13px;
        font-weight: 300;
      }

      #pac-input {
        background-color: #fff;
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
        margin-left: 12px;
        padding: 0 11px 0 13px;
        text-overflow: ellipsis;
        width: 400px;
      }

      #pac-input:focus {
        border-color: #4d90fe;
      }

      #title {
        color: #fff;
        background-color: #4d90fe;
        font-size: 25px;
        font-weight: 500;
        padding: 6px 12px;
      }
    </style>
  </head>
  <body>
  <h1>Your To-Do List</h1>
    <div id="map"></div>
    <div id="infowindow-content">
      <span id="place-name" class="title"></span><br />
      <span id="place-address"></span>
    </div>

    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA5nPPyp2vkIqulwFAQyarT4CQZY4ZwlQ4&callback=initMap&libraries=places&v=weekly&solution_channel=GMP_CCS_autocomplete_v1"
      defer
    ></script>
  </body>
</html>



<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Todo App</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <!-- Custom CSS -->
  <style>
    /* Custom Styles */
    body {
      font-family: Arial, sans-serif;
      background-color: #f8f9fa;
    }
    .container {
      margin-top: 50px;
    }
    h1 {
      color: #007bff;
      margin-bottom: 30px;
      text-align: center;
    }
    .todo-item {
      background-color: #fff;
      border: 1px solid #ced4da;
      border-radius: 5px;
      padding: 15px;
      margin-bottom: 15px;
    }
    .todo-item p {
      margin-bottom: 5px;
    }
    .btn-primary {
      background-color: #007bff;
      border-color: #007bff;

      margin-bottom: 30px;
    }
    .btn-primary:hover {
      background-color: #0056b3;
      border-color: #0056b3;
    }
    .btn-secondary {
      background-color: #6c757d;
      border-color: #6c757d;
      margin-bottom: 30px;
    }
    .btn-secondary:hover {
      background-color: #545b62;
      border-color: #4e555b;
    }
  </style>
</head>
<body>

<div class="container">
  <!-- Notice -->
  <% if notice.present? %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <!-- Todo List -->
  
  <div id="todos">
    <% @todos.each do |todo| %>
      <div class="todo-item">
        <%= render todo %>
        <p>
          <%= link_to "Show this todo", todo, class: "btn btn-primary btn-sm" %>
        </p>
      </div>
    <% end %>
  </div>


  <!-- Actions ________________________________________________________________________________________ -->
  <div class="text-center mt-4">
    <%= link_to "New Todo", new_todo_path, class: "btn btn-primary mr-2" %>
    <%= link_to "Browse Locations", locations_path, class: "btn btn-secondary" %>
  </div>
</div>

<!-- Bootstrap JS (optional) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/show.html.erb
<div class="container">
  <% if notice.present? %>
    <div class="alert alert-success mt-4" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <%= render @todo %>

  <div class="mt-4">
    <%= link_to "Edit this todo", edit_todo_path(@todo), class: "btn btn-primary mr-2" %> |
    <%= link_to "Back to todos", todos_path, class: "btn btn-secondary mr-2" %>
    <%= button_to "Destroy this todo", @todo, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
  </div>
</div>

app/views/todos/task.html.erb
<h1 class="text-2xl">Todo List</h1>

<%= form_with(model: Todo.new, class: "my-10") do |form| %>
  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, placeholder: "new todo", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-2/4" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
  <table class="w-3/5 mt-10 border-separate table-auto text-slate-500">
  <thead>
    <tr>
      <th class="p-3 text-sm font-semibold text-left text-gray-700 bg-gray-200">ID</th>
      <th class="p-3 text-sm font-semibold text-left text-gray-700 bg-gray-200">Description</th>
    </tr>
  </thead>
  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td class="px-3 py-4 text-sm font-normal text-left text-gray-600 bg-gray-50">
          <%= todo.id %>
        </td>
        <td class="px-3 py-4 text-sm font-normal text-left text-gray-600 bg-gray-50">
          <%= todo.description %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>